spring.application.name=planner

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://dpg-d8mf227lk1mc738k0edg-a.singapore-postgres.render.com:5432/event_planner_7w1q
spring.datasource.username=event_user
spring.datasource.password=6wVdtO45b43mpGUVcMkwS3SsvRuODoCF
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect