spring.application.name=planner

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/event_planner
spring.datasource.username=event_planner
spring.datasource.password=event_planner
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/master